spring:
  datasource:
    url: jdbc:h2:mem:studentdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8001

logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true


app:
  name: Student Management System
  version: 1.0.0
  enableFeatureX: true


info:
  app:
    name: Student Management System
    version: 1.0.0
    description: Development environment API
