spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bishaldb
    driver-class-name: org.postgresql.Driver
    username: bishal
    password: bishal1212
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
    metrics:
      enabled: true

info:
  app:
    name: Student Management API
    version: 1.0.0
    description: API for managing student records
