spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bishaldb
    driver-class-name: org.postgresql.Driver
    username: bishal
    password: bishal1212

  jpa:
    hibernate:
      ddl-auto: update  #Automatically creates/upate tables
    show-sql: true     #Show sql statement in log
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  #Formal SQL for readability

server:
  port: 8080

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
    metrics:
      enabled: true

info:
  app:
    name: Student Management API
    version: 1.0.0
    description: API for managing student records

app:
  name: Student Management System
  version: 1.0.0
  enableFeatureX: false
